{{- if .Values.flower.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobo.fullname" . }}-flower
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kobo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower 
{{- end }}