{{- if .Values.kobocat.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kobo.fullname" . }}-kobocat
  minReplicas: {{ .Values.kobocat.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.kobocat.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.kobocat.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.kobocat.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.kobocat.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.kobocat.autoscaling.targetMemory }}
    {{- end }}
{{- end }}
