{{- if .Values.preInstall.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
    checksum/secret: {{ include (print $.Template.BasePath "/kobocat/secrets.yaml") . | sha256sum }}
    checksum/configmap: {{ include (print $.Template.BasePath "/kobocat/configmap.yaml") . | sha256sum }}
    tag: "{{ .Values.kobocat.image.tag }}"
spec:
  activeDeadlineSeconds: {{ default 600 .Values.preInstall.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kobocat-job
        {{- include "kobo.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "{{ .Values.kobocat.image.repository }}:{{ .Values.kobocat.image.tag }}"
        imagePullPolicy: {{ .Values.kobocat.image.pullPolicy }}
        command: ["./manage.py","migrate"]
        env:
          - name: DJANGO_SECRET_KEY
            value: {{ required "djangoSecret is a required value." .Values.kobotoolbox.djangoSecret }}
          {{- if .Values.postgresql.enabled }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ default (include "kobo.postgresql.fullname" .) .Values.postgresql.auth.existingSecret }}
                key: postgres-password
          - name: DATABASE_URL
            value: {{ (include "kobo.postgresql.kc_url" .) }}
          {{- else }}
          - name: DATABASE_URL
            value: {{ required "kobocatDatabase required" .Values.kobotoolbox.kobocatDatabase }}
          {{- end }}
          {{ if .Values.kobotoolbox.redis }}
          - name: ENKETO_REDIS_MAIN_URL
            value: {{ printf "%s/0%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | quote }}
          {{- end }}
        {{- range $k, $v := .Values.kobocat.env.normal }}
          - name: {{ $k }}
            value: {{ $v | quote }}
        {{- end }}
        {{- with .Values.kobocat.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.kobocat.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
