upstream backend {
    ip_hash;
    server 127.0.0.1:8000;
}

map $arg_format $schema_v2_file {
    default /schema_v2.yaml;
    json    /schema_v2.json;
}

map $arg_format $schema_openrosa_file {
    default /schema_openrosa.yaml;
    json    /schema_openrosa.json;
}

map $arg_format $schema_type {
    default application/yaml;
    json    application/json;
}

server {

    client_max_body_size 100M;
    large_client_header_buffers 8 16k;

    {{ if .Values.kpi.nginx.large_headers.enabled -}}
    # Proxy buffer settings to handle large headers
    proxy_buffer_size {{ .Values.kpi.nginx.large_headers.proxy_buffer_size | default "32k" }};
    proxy_buffers {{ .Values.kpi.nginx.large_headers.proxy_buffers | default "8 32k" }};
    proxy_busy_buffers_size {{ .Values.kpi.nginx.large_headers.proxy_busy_buffers_size | default "64k" }};
    proxy_temp_file_write_size {{ .Values.kpi.nginx.large_headers.proxy_temp_file_write_size | default "64k" }};
    proxy_max_temp_file_size {{ .Values.kpi.nginx.large_headers.proxy_max_temp_file_size | default "1024m" }};
    proxy_buffering {{ .Values.kpi.nginx.large_headers.proxy_buffering | default "on" }};
    {{- end }}

    {{ $timeout := .Values.kpi.nginx.timeout | default (.Values.global.timeout | default 120) -}}
    # Set timeout values from Helm values
    proxy_read_timeout {{ $timeout }};
    proxy_send_timeout {{ $timeout }};
    {{- if .Values.kpi.nginx.timeout }}
    proxy_connect_timeout {{ .Values.kpi.nginx.timeout }};
    send_timeout {{ .Values.kpi.nginx.timeout }};
    {{- end }}

    gzip on;
    gzip_disable "msie6";
    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        image/svg+xml;

    location ~ ^/protected-s3/(.*)$ {
        # Allow internal requests only, i.e. return a 404 to any client who
        # tries to access this location directly
        internal;
        # Name resolution won't work at all without specifying a resolver here.
        # Configuring a validity period is useful for overriding Amazon's very
        # short (5-second?) TTLs.
        resolver 8.8.8.8 8.8.4.4 valid=300s;
        resolver_timeout 10s;
        # Everything that S3 needs is in the URL; don't pass any headers or
        # body content that the client may have sent
        proxy_pass_request_body off;
        proxy_pass_request_headers off;

        # Stream the response to the client instead of trying to read it all at
        # once, which would potentially use disk space
        proxy_buffering off;

        # Don't leak S3 headers to the client. List retrieved from:
        # https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html
        proxy_hide_header x-amz-delete-marker;
        proxy_hide_header x-amz-id-2;
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-version-id;

        # S3 will complain if `$1` contains non-encoded special characters.
        # KoBoCAT must encode twice to make sure `$1` is still encoded after
        # NGINX's automatic URL decoding.
        proxy_pass $1;
    }

    location /static {
        alias /static;
        add_header Strict-Transport-Security "max-age={{ .Values.kpi.nginx.hsts_max_age }}" always;
    }

    # Bypass Django endpoint and serve the static schema files generated by
    # `./scripts/generate_openapi_schemas.sh` in the KPI container.
    location ~ ^/api/(v2|openrosa)/schema$ {
        return 301 /api/$1/schema/$is_args$args;
    }

    location = /api/v2/schema/ {
       root /static/openapi;
       try_files $schema_v2_file =404;
       add_header Content-Type $schema_type always;
       add_header Strict-Transport-Security "max-age={{ .Values.kpi.nginx.hsts_max_age }}" always;
    }

    location = /api/openrosa/schema/ {
       root /static/openapi;
       try_files $schema_openrosa_file =404;
       add_header Content-Type $schema_type always;
       add_header Strict-Transport-Security "max-age={{ .Values.kpi.nginx.hsts_max_age }}" always;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header Strict-Transport-Security; # Must be removed to not duplicate the header
        add_header Strict-Transport-Security "max-age={{ .Values.kpi.nginx.hsts_max_age }}" always;
        proxy_pass http://backend;
    }

    listen 80;
    server_tokens off;
}
