{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kobo.serviceAccountName" . }}
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecrets }}
{{- range .Values.imagePullSecrets }}
imagePullSecrets:
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
