apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kobo.fullname" . }}-kpi
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.kobotoolbox.djangoSecret | b64enc | quote }}
{{ if .Values.kobotoolbox.kobocatDatabase }}
  KC_DATABASE_URL: {{ .Values.kobotoolbox.kobocatDatabase | b64enc | quote }}
{{ end }}
{{ if .Values.kobotoolbox.mongoDatabase }}
  MONGO_DB_URL: {{ .Values.kobotoolbox.mongoDatabase | b64enc | quote }}
{{ end }}
{{ if .Values.kobotoolbox.redis }}
  REDIS_SESSION_URL: {{ printf "%s/1%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | b64enc | quote }}
  SERVICE_ACCOUNT_BACKEND_URL: {{ printf "%s/6%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | b64enc | quote }}
  CELERY_BROKER_URL: {{ printf "%s/2%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | b64enc | quote }}
  CACHE_URL: {{ printf "%s/4%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | b64enc | quote }}
  ENKETO_REDIS_MAIN_URL: {{ printf "%s/0%s" .Values.kobotoolbox.redis .Values.kobotoolbox.redisParameters | b64enc | quote }}
{{ else if .Values.kobotoolbox.redisSession }}
  REDIS_SESSION_URL: {{ .Values.kobotoolbox.redisSession | b64enc | quote }}
{{ if .Values.kobotoolbox.serviceAccountBackend }}
  SERVICE_ACCOUNT_BACKEND_URL: {{ .Values.kobotoolbox.serviceAccountBackend | b64enc | quote }}
{{ end }}
{{ end }}
  ENKETO_API_KEY: {{ required "enketoApiKey required" .Values.kobotoolbox.enketoApiKey | b64enc | quote }}
  # -- Alias for Enketo API key. Still in used but deprecated
  ENKETO_API_TOKEN: {{ required "enketoApiKey required" .Values.kobotoolbox.enketoApiKey | b64enc | quote }}
{{- range $k, $v := .Values.kpi.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
